#!/bin/bash
if [ -z "$1" ]
  then
    echo "pm2 [raysoda|rapixel|osoky|drypot]"
    exit 1
fi
args=(
    start
    code/main/main.mjs
    --name $1
    --exp-backoff-restart-delay=2000
    --
    -c config-live/${1}-live.json
)
export NODE_ENV=production
pm2 "${args[@]}"
